<a href="https://colab.research.google.com/github/duartele/exerc-jupyternotebook/blob/main/PrimeirosComandos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
peso = 83.9
idade = 19

pot = idade ** 2 #Elevar a um potencia - 2 neste exemplo
mod = idade % 10 #Resto da divisao inteira
div = idade // 3 #Divisao inteira

print('pot = ', pot,'mod = ', mod, 'div = ', div)
print(type(peso))
type(peso) #Na ultima linha nao precisamos usar o comando print

pot =  361 mod =  9 div =  6
<class 'float'>


float

In [ ]:
nome = 'Leandro'
nome += ' ' + 'Duarte' #Simbolo usado para concatenar
print(nome)

lista = [1, 2, 3, 4]
lista += [5, 6, 7, 8] + [9, 10]
print(lista) #Assim como uma string, ao usar '+' nos concatenamos e nao somamos
print(lista[0]) #Primeiro elemento
print(lista[-1]) #'Ultimo elemento
print(lista[1:6]) #Segundo elemento ate o quinto elemento
print(lista[-4:]) #quartultimo ate o ultimo elemento

variado = [10, 25.5,'Leandro', True, ['Sao Paulo', 'Rio de Janeiro', 'Parana']] #Na lista podemos ter varios tipos, inclusive possuir outras listas

variado

Leandro Duarte
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
10
[2, 3, 4, 5, 6]
[7, 8, 9, 10]


[10, 25.5, 'Leandro', True, ['Sao Paulo', 'Rio de Janeiro', 'Parana']]

In [ ]:
def somaEprod(a,b):
  s = a + b
  p = a * b
  return s, p #Diferentemente de Java, a funcao pode ter mais de um retorno

In [ ]:
s,p = somaEprod(2,2) #pode fazer assim para separar os valores
print(s,p)
somaEprod(2,2) #Ou pode armezenar o resultado numa Tupla

4 4


(4, 4)

In [ ]:
import random

print(random.randint(10, 20)) #Importando assim, precisa especificar sempre a biblioteca (random.)

18


In [ ]:
from random import randint

print(randint(10, 20)) #Aqui basta chamar diretamente a funcao

10


# Blibiotecas para Ciencia de Dados: 1) Numpy

Para mais informacoes acesse https://numpy.org/doc/

In [34]:
import numpy as np #Tao comum esse apelido que o proprio Notebook o sugere
'''arrays - eixo 0 vertical, eixo 1 horizontal
([1,2,3,4])               ([2,3,1],[4,5,1])               ([])
shape(4,) 1 dim           shape(2,3) 2dim                 matriz de cores RGB shape (3,200,200)
'''
a = np.array([2, 3, 5, 6, 8])
a.ndim #numero de dimensoes - nesse ex = 1
a.shape #formato - 5 elementos nessa unica dimen

(5,)

In [41]:
a = np.zeros((3,2)) # Gera uma matriz de zeros (3 linhas x 2 colunas)
a = np.ones((1,2)) # Gera uma matriz de 1 (1 x 2)
a = np.ones((3,2,4)) #Matriz 3D como se fossem 3 matrizes 2x4
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
a = np.arange(5) #Comando para criar vetores (de 0 ate 4)
a = np.arange(2,5) #Comando para criar vetores (de 2 ate 4) como um fatiamento
a

array([2, 3, 4])

In [45]:
a = np.random.random((3,2)) # gera aleatorios entre 0 e 1
b = np.random.randint(20,size=(3,2)) # gera aleatorios entre 0 e 20 formando uma matriz 3x2
b 

array([[ 8, 17],
       [ 3,  5],
       [10, 17]])